version: '3.7'
services:
  build_android:
    image: circleci/node:9.11.2-jessie
    user: root
    volumes:
      - ./:/source
    working_dir: /source
    environment:
      - NPM_TOKEN=${NPM_TOKEN}