name: Build iOS
description: Builds the iOS app

runs:
  using: composite
  steps:
    - name: Build iOS
      shell: bash
      run: |
        ls -la Rokt.Widget/
        cd RoktSampleApp
        npm install
        npx react-native build-ios
        app_path=$(find ~/Library/Developer/Xcode/DerivedData -name "RoktSampleApp.app" -type d | head -1)
        if [ -z "$app_path" ]; then
          # Fallback to local build directory
          app_path=$(find ios/build -name "RoktSampleApp.app" -type d | head -1)
        fi
        if [ -z "$app_path" ]; then
          echo "Error: Could not find built app"
          exit 1
        fi
        cp -r $app_path RoktSampleApp/ios/RoktSampleApp.app

    - name: Upload iOS artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
      with:
        name: rokt-sdk-react-native-ios
        path: RoktSampleApp/ios/RoktSampleApp.app
        retention-days: 7
