steps:
   - block: ":whale: Run UI tests"
     prompt: "Confirm running UI tests on device farm?"

   - wait
   - name: ':hammer: Build and UI Test trigger'
     commands:
      - ls
      - cd ./RoktSampleApp
      - sudo apt install curl
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - sudo apt-get install -y nodejs 
      - npm install
      - ls
      - cd ./android
      - bundle install
      - echo accesskey $DEVICE_FARM_STAGE_ACCESS_KEY
      - echo secretkey $DEVICE_FARM_STAGE_SECRET_KEY
      - bundle exec fastlane deviceFarmUITest
     artifact_paths:
       - "app/**/*.apk"
     plugins:
      - docker-compose#v3.0.0:
          config: ./docker/docker-compose.yml
          run: build_android
      - seek-oss/aws-sm#v2.0.0:
          env:
            STORE_PASSWORD:
              secret-id: 'stage-android-sdk-buildkite'
              json-key: '.STORE_PASSWORD'
            KEY_ALIAS:
              secret-id: 'stage-android-sdk-buildkite'
              json-key: '.KEY_ALIAS'
            KEY_PASSWORD:
              secret-id: 'stage-android-sdk-buildkite'
              json-key: '.KEY_PASSWORD'
            DEVICE_FARM_STAGE_ACCESS_KEY:
              secret-id: 'stage-android-sdk-buildkite'
              json-key: '.DEVICE_FARM_STAGE_ACCESS_KEY'
            DEVICE_FARM_STAGE_DEVICE_POOL:
              secret-id: 'stage-android-sdk-buildkite'
              json-key: '.DEVICE_FARM_STAGE_DEVICE_POOL'
            DEVICE_FARM_STAGE_PROJECT_NAME:
              secret-id: 'stage-android-sdk-buildkite'
              json-key: '.DEVICE_FARM_STAGE_PROJECT_NAME'
            DEVICE_FARM_STAGE_SECRET_KEY:
              secret-id: 'stage-android-sdk-buildkite'
              json-key: '.DEVICE_FARM_STAGE_SECRET_KEY'
     agents:
     - "queue=stage-us-west-2-default"       
  
     - block: ":whale: Publish"
       prompt: "Confirm publish Widget to npm?"

   - wait
   - name: ':rocket: Publish'
     commands:
      - cd ./Rokt.Widget && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - npm publish --access=public

     plugins:
      - docker-compose#v3.0.0:
          config: ./docker/docker-compose-node.yml
          run: build_android 

      - seek-oss/aws-sm#v2.0.0:
          env:
            STORE_PASSWORD:
              secret-id: 'stage-android-sdk-buildkite'
              json-key: '.NPM_TOKEN'    
     agents:
     - "queue=eng-default"  
   
