env:
  ENG_ACCOUNT: "035088524874"
  ECR_HOST: ${ENG_ACCOUNT}.dkr.ecr.us-west-2.amazonaws.com
  MAC_BK_AGENT: eng-prod-us-west-2-mac-arm-macos-build-medium
  ENG_BK_AGENT: eng-default

steps:
  - label: "TEST"
    commands:
      - cd infra
      - ./modify_native_ios_version.sh $(buildkite-agent meta-data get "IOS_NATIVE_VERSION") ../Rokt.Widget/rokt-react-native-sdk.podspec
      - ./modify_native_android_version.sh $(buildkite-agent meta-data get "ANDROID_NATIVE_VERSION") ../Rokt.Widget/android/build.gradle
      - cat ../Rokt.Widget/rokt-react-native-sdk.podspec
      - cat ../Rokt.Widget/android/build.gradle
    agents:
      queue: ${ENG_BK_AGENT}