env:
  ENG_ACCOUNT: "035088524874"
  ECR_HOST: ${ENG_ACCOUNT}.dkr.ecr.us-west-2.amazonaws.com
  MAC_BK_AGENT: eng-prod-us-west-2-mac-arm-macos-build-medium
  ENG_BK_AGENT: eng-default

steps:
  - label: "TEST"
    commands:
      - cd infra
      - sh modify_native_ios_version.sh $(buildkite-agent meta-data get "IOS_NATIVE_VERSION") ../Rokt.Widget/rokt-react-native-sdk.podspec
      - sh modify_native_android_version.sh $(buildkite-agent meta-data get "ANDROID_NATIVE_VERSION") ../Rokt.Widget/android/build.gradle
      - cd ../Rokt.Widget
      - npm version $(buildkite-agent meta-data get "VERSION")
      - npm install && npm run build && npm run pack
    plugins:
      - docker#v5.6.0:
          image: "${ECR_HOST}/cached/node:17.2.0-alpine"
          user: "root"
          mount-buildkite-agent: true
      - artifacts#v1.9.0:
          upload: "Rokt.Widget/*.tgz"
    agents:
      queue: ${ENG_BK_AGENT}
    timeout_in_minutes: 15