version: '3.7'
services:
  build_android:
    build:
      context: ./
    mage: circleci/android@sha256:061e2535826cc3fe4c4a440e716bf06c36c80401ee635c339c6803b3e427ebb3
    user: root
    volumes:
      - ./:/source
    working_dir: /source
    environment:
      - DEVICE_FARM_STAGE_ACCESS_KEY=${DEVICE_FARM_STAGE_ACCESS_KEY}
      - DEVICE_FARM_STAGE_DEVICE_POOL=${DEVICE_FARM_STAGE_DEVICE_POOL}
      - DEVICE_FARM_STAGE_E2E_DEVICE_POOL=${DEVICE_FARM_STAGE_E2E_DEVICE_POOL}
      - DEVICE_FARM_STAGE_PROJECT_NAME=${DEVICE_FARM_STAGE_PROJECT_NAME}
      - DEVICE_FARM_STAGE_SECRET_KEY=${DEVICE_FARM_STAGE_SECRET_KEY}
      - UPLOAD_AWS_ACCESS_KEY_ID=${UPLOAD_AWS_ACCESS_KEY_ID}
      - UPLOAD_AWS_SECRET_ACCESS_KEY=${UPLOAD_AWS_SECRET_ACCESS_KEY}
      - STORE_PASSWORD=${STORE_PASSWORD}
      - KEY_ALIAS=${KEY_ALIAS}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - APPCENTER_API_TOKEN=${APPCENTER_API_TOKEN}
      - APPCENTER_APP_OWNER=${APPCENTER_APP_OWNER}
      - APPCENTER_APP_NAME=${APPCENTER_APP_NAME}
      - APPCENTER_APP_DESTINATION=${APPCENTER_APP_DESTINATION}
      - BUILDKITE_BUILD_NUMBER=${BUILDKITE_BUILD_NUMBER}
      - BUILDKITE_BRANCH=${BUILDKITE_BRANCH}
      - BUILDKITE_MESSAGE=${BUILDKITE_MESSAGE}
