# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'RoktSampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#  use_flipper!()
  use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })

  target 'RoktSampleAppTests' do
      inherit! :complete
      # Pods for testing
  end
  
  post_install do |installer|
    react_native_post_install(installer)
  end
end
