name: Download and Flatten Artifacts
description: Downloads artifacts using a pattern and flattens the directory structure

inputs:
  pattern:
    description: Artifact name pattern for downloads
    required: true
  path:
    description: Path where artifacts should be downloaded
    required: true
  file-extension:
    description: File extension to flatten (e.g., tgz, apk, zip)
    required: false
    default: tgz

runs:
  using: composite
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        pattern: ${{ inputs.pattern }}
        path: ${{ inputs.path }}

    - name: Flatten downloaded artifacts
      shell: bash
      run: |
        # Move files with specified extension from subdirectories to target path root
        find "${{ inputs.path }}" -name "*.${{ inputs.file-extension }}" -exec mv {} "${{ inputs.path }}/" \;
        # Clean up empty subdirectories
        find "${{ inputs.path }}" -type d -empty -delete 2>/dev/null || true
        echo "Flattened *.${{ inputs.file-extension }} files in ${{ inputs.path }}"
